# Putting It All Into Practice {.tabset}

Once you have filled out the [Research Design Form](research-design.html) and received funding, or perhaps even completed your project, you will confront a series of other challenges. 

This module currently lists a few of those challenges with associated links and references that might prove useful, including: workflow, Pre-Analysis Plans, 

## Core Content

### Workflow

How will you remember what you did a year, or two, or ten, after you did it? How will you ensure that the tables and graphs and results that you use to guide policy decisions are not the result of copy and paste errors? Or that your code did not involve an inadvertantly reverse-coded variable, yielding the opposite conclusion than you have just told the Minister of Health? Although no approach can prevent all errors, some basic approaches to organizing work can help you. These involve, at their root, a move from someone doing quick essays to turn in at the end of a term (essays never to be subsequently serious revisited) to someone participating in a decades-(or centuries-)long collaboration with other scholars and policy makers across time and space.

  - [On using 'Dark Logic' to anticipate failure and plan for it](https://jech.bmj.com/content/jech/69/1/95.full.pdf).

  - The [pre-mortem approach to project management](https://en.wikipedia.org/wiki/Pre-mortem) approach to project management in which the team imagines that a project has failed before launching the project.

### Dealing with real world constraints

 - Working with partners: humility and respect and listening
 - Budgets and physical limits on the size of the experimental pool (limits on control of the randomization)
    - Example: Cluster-randomized designs with small number of clusters

### Pre-analysis plans

### How to present results table or graph.

 - Tufte on Ink to Information Ratio.
 - @gerber_field_2012, Chapter 13

### External validity, Generalization, Scaling

## Resources:

### EGAP Methods Guide

  - EGAP Methods Guide [10 Things to Know About Project Workflow](https://egap.org/resource/10-things-to-know-about-project-workflow/) (which builds on @bowers2016future).
 - EGAP Methods Guide [10 Things to Know About Pre-Analysis Plans](https://egap.org/resource/10-things-to-know-about-pre-analysis-plans/)

### Books, Chapters, and Articles

  - @cartwright2012evidence warn about simplistic use of RCT results to guide public policy.

  - See also @bowerstesta2019epp and especially their discussion of @giacomini2009theory in regards the importance of theory in connecting research design and public policy.

### EGAP Policy Briefs

