# The Research Design Process

This book aims to help you understand and design randomized field experiments.  But before we dive into the details of research design, we need a good research question -- a question that will advance knowledge or help make a policy decision or both.  There is no simple recipe for finding or developing a good scientific or policy question, but our theories play an important role in articulating good questions that underlie to impactful research.  After formulating our question, we develop the best design possible within our resource constraints, using our knowledge of causal inference and statistics from the modules that follow.  

This module introduces the [EGAP Research Design
Form](https://egap.github.io/learningdays-resources/Exercises/design-form.Rmd), a checklist to guide you through the many stages of the research process.  The Learning Days workshops are organized around the Research Design Form.  We also point you towards the [DeclareDesign](http://declaredesign.org) software package to explore the implications of different choices we could make for our research designs.  Finally, this module discusses pre-analysis plans and pre-registration.  When plan our analyses and make these plans public, we improve our chances of persuading others with our results.

## Core Content

- What makes a **good research question**? A good research question advances science and/or is a question the answer to which will change a policy decision.

- Certain **research designs** are better able to address certain questions. We want to choose the design that best answers our key questions within our constraints.

- The questions we ask arise, often implicitly, from our values and from our understanding about how the world works. These **theories** structure our questions --- make the questions relevant. And the experiments that we execute teach us about the theory --- we hope that the evidence and data arising from these research designs improves our understanding.

- What are the **core components of a research design**?

- Introduce core components of the [EGAP Research Design Form](https://egap.github.io/learningdays-resources/Exercises/design-form.html). 

- Introduce a research design software package, [DeclareDesign](http://declaredesign.org).

- The move in social science towards the **review of designs, rather than outcomes**.

 - **Pre-registration**: what is it? why should we do it? how should we do it?


## Slides

Below are slides with the core content that we cover in our lecture on research design. You can directly use these slides or make your own local copy and edit.

- [R Markdown Source](https://egap.github.io/learningdays-resources/Slides/researchdesignform-slides.Rmd)

- [PDF Version](https://egap.github.io/learningdays-resources/Slides/researchdesignform-slides.pdf)

- [HTML Version](https://egap.github.io/learningdays-resources/Slides/researchdesignform-slides.html)

You can also see the slides used in previous EGAP Learning Days:

 - [The DeclareDesign presentation from EGAP Learning Days at Universidad Cat贸lica del Uruguay, Montevideo, March 2018](https://egap.github.io/learningdays-resources/Slides/Examples/declare_design-montevideo.pdf)

 - [The DeclareDesign presentation from EGAP Learning Days in Salima, Malawi, February 2017](https://egap.github.io/learningdays-resources/Slides/Examples/declare_design-malawi.pdf)

 - [The DeclareDesign presentation from EGAP Learning Days at Universidad Diego Portales in Santiago, Chile, May 2016](https://egap.github.io/learningdays-resources/Slides/Examples/declare_design-santiago.pdf)

You can also see slides for Design Talks in previous EGAP Learning Days, where presenters focus on issues that come up in designing the research, rather than the results:

 - [Design Talk from EGAP Learning Days at African School of Economics, Benin, March 2018](https://egap.github.io/learningdays-resources/Slides/Examples/research_design_2-benin.pdf)

 - [Design Talk 1 from EGAP Learning Days at Universidad Cat贸lica del Uruguay, Montevideo, March 2018](https://egap.github.io/learningdays-resources/Slides/Examples/research_design_1-montevideo.pdf)

 - [Design Talk 2 from EGAP Learning Days at Universidad Cat贸lica del Uruguay, Montevideo, March 2018](https://egap.github.io/learningdays-resources/Slides/Examples/research_design_2-montevideo.pdf)

 - [Design Talk 3 from EGAP Learning Days at Universidad Cat贸lica del Uruguay, Montevideo, March 2018](https://egap.github.io/learningdays-resources/Slides/Examples/research_design_3-montevideo.pdf)

 - [Design Talk 1 from EGAP Learning Days at Universidad Diego Portales in Santiago, Chile, May 2016](https://egap.github.io/learningdays-resources/Slides/Examples/research_design_1-santiago.pdf)

 - [Design Talk 2 from EGAP Learning Days at Universidad Diego Portales in Santiago, Chile, May 2016](https://egap.github.io/learningdays-resources/Slides/Examples/research_design_2-santiago.pdf)

 - [Design Talk 3 from EGAP Learning Days at Universidad Diego Portales in Santiago, Chile, May 2016](https://egap.github.io/learningdays-resources/Slides/Examples/research_design_3-santiago.pdf)

 - [Design Talk from EGAP Learning Days in Guatemala City, Guatemala, August 2017](https://egap.github.io/learningdays-resources/Slides/Examples/research_design-guatemala.pdf)

## Design Form and Pre-Registration

- [EGAP Research Design Form](https://egap.github.io/learningdays-resources/Exercises/design-form.html). A checklist we created for the Learning Days to guide you through the stages of the research process.
     - [Docx Version](https://egap.github.io/learningdays-resources/Exercises/design-form.docx)

     - [PDF Version](https://egap.github.io/learningdays-resources/Exercises/design-form.pdf)

     - [HTML Version](https://egap.github.io/learningdays-resources/Exercises/design-form.html)

- Links to repositories for pre-registration/pre-analysis plans:

    - EGAP registry, hosted by OSF (https://egap.org/registry/)

    - AEA RCT registry (https://www.socialscienceregistry.org/)

    - OSF (https://osf.io/registries)

- Examples of other pre-registrations/pre-analysis plans:

    - SMS Messages in Mozambique from the [US Federal Government](https://oes.gsa.gov/projects/sms-mozambique/)

    - Police Body-Cameras from the [Lab @ DC](https://osf.io/472zh)

## Resources

### EGAP Methods Guides

- EGAP Methods Guide [10 Things to Know about Pre-Analysis Plans](https://egap.org/resource/10-things-to-know-about-pre-analysis-plans/)

- EGAP Methods Guide [10 Things to Know about Measurement in Experiments](https://egap.org/resource/10-things-to-know-about-measurement-in-experiments/)


### Books, Chapters, and Articles

- [Preregistration as a Tool for Strengthening Federal Evaluation](https://oes.gsa.gov/assets/files/preregistration-as-a-tool-in-federal-evaluation.pdf)  A white paper from the US Government's Office of Evaluation Sciences.  You can also see examples of their pre-analysis plans on all of [their field experiment pages](https://oes.gsa.gov/work/).

- [@christensen_transparent_2019] The book summarizes new approaches in social science research on transparency and reproducibility.

- [@gerber_field_2012, Chapter 12] Includes some examples of experimental research designs.

### Tools

- [DeclareDesign](https://declaredesign.org/), an exciting and comprehensive set of software tools for describing, assessing, and conducting empirical research.

