# Statistical Power and Design Diagnosands {.tabset}

Before we run a study, we would like to know whether a particular design has the statistical power to detect an effect if it exists.  It is difficult to learn from an under-powered study, since it would be unclear whether a null result indicates that there is no effect or just that we failed to detect a non-zero effect that exists.  A power analysis can help you improve your design and reallocate your resources; it may even help you decide against conducting the study.

In this module, we introduce statistical power, core approaches to calculating power through analytical calculations or through simulation, and how design features such as blocking, covariate adjustment, and clustering impact power.

## Core Content

 - **Statistical power** is the ability of a study to detect an effect given that it exists.
 
 - **Power analysis** is something we do before a study.  It helps you figure out the sample you need or what effects you can detect. It is an essential step in research design and helps you communicate your design.

 - Common approaches to power calculation:
 
      - **Analytical** power calculations (using a formula)
 
      - **Simulations** (for example, using DeclareDesign)

 - **Covariate adjustment** and **blocking** can increase power.

 - For **clustered designs** you need to take account of the intra-cluster correlation (the within cluster variance relative to the overall variance).
 
 - Power is closely liked to [study design](the-research-design-process.html), [hypothesis testing](hypothesis-testing.html) and [estimation](estimands-and-estimators.html).

## Slides
Below are slides with the core content that we cover in our lecture on power. You can directly use these slides or make your local copy and edit.

 - [R Markdown Source](https://egap.github.io/learningdays-resources/Slides/power-slides.Rmd)

 - [PDF version](https://egap.github.io/learningdays-resources/Slides/power-slides.pdf)

 - [HTML version](https://egap.github.io/learningdays-resources/Slides/power-slides.html)

You can also see the slides used in previous EGAP Learning Days:

 - [The power presentation from EGAP Learning Days at the African School of Economics, Abomey-Calavi, June 2019](https://egap.github.io/learningdays-resources/Slides/Examples/power-benin.pdf)

 - [The power presentation from EGAP Learning Days at Universidad de Los Andes, Bogotá, April 2019](https://egap.github.io/learningdays-resources/Slides/Examples/power-bogota.pdf)

 - [The power presentation from EGAP Learning Days at Universidad Católica del Uruguay, Montevideo, March 2018](https://egap.github.io/learningdays-resources/Slides/Examples/power-montevideo.pdf)

 - [The power presentation from EGAP Learning Days in Guatemala City, Guatemala, August 2017](https://egap.github.io/learningdays-resources/Slides/Examples/power-guatemala.html)

 - [The power presentation from EGAP Learning Days in Salima, Malawi, February 2017](https://egap.github.io/learningdays-resources/Slides/Examples/power-malawi.pdf)

 - [The power presentation from EGAP Learning Days at Universidad Diego Portales in Santiago, Chile, May 2016](https://egap.github.io/learningdays-resources/Slides/Examples/power-santiago.pdf)


## Resources

### EGAP Methods Guides

 - EGAP Methods Guide [10 Things to Know about Statistical Power](https://egap.org/resource/10-things-you-need-know-about-statistical-power/)

 - EGAP Methods Guide [10 Things to Know about Covariate Adjustment](https://egap.org/resource/10-things-to-know-about-covariate-adjustment/)
 
 - EGAP Methods Guide [10 Things Your Null Results Might Mean](https://egap.org/resource/10-things-your-null-result-might-mean/)

### EGAP Policy Briefs and PAPs

Some examples of power analysis in designs:

 - [Pre-Analysis Plan. Accountability Can Transform (ACT) Health: A Replication and Extension of Bjorkman and Svensson (2009)](https://osf.io/qxwmu/)
 
 - [EGAP Policy Brief 58: Can bottom-up accountability generate improvements in health outcomes?](https://egap.org/resource/does-bottom-up-accountability-work-evidence-from-uganda/)


### Tools
 - Interactive power analysis
 
      - [EGAP Power Calculator](https://egap.shinyapps.io/power-app/)
 
      - [rpsychologist](https://rpsychologist.com/d3/NHST/)

 - R packages for power analysis
 
      - [pwr](https://cran.r-project.org/web/packages/pwr/index.html)
 
      - [DeclareDesign](https://cran.r-project.org/web/packages/DeclareDesign/index.html), see also <https://declaredesign.org/>

