# Threats to the Internal Validity of Randomized Experiments {.tabset}

Randomized experiments can run into issues that undermine their ability to demonstrate causal effects -- that is, threaten the internal validity of randomized experiments.  Some units might be missing outcome data and that missingness may be due to the treatment.  They may not take the treatment status assigned to them or be subject to spillover effects from a treated neighbor. 

In this module, we cover some common threats and some best practices to avoid or work around them.

## Core content {.tabset}

 - Review the three core assumptions discussed in the [causal inference ](causal-inference.html) module.

 - We have said "Analyze as you randomize" elsewhere ([estimands and estimators](estimands-and-estimators.html)). Remember that you randomized treatment **assignment**, not whether the treatment is received or whether a unit participates in data collection.  

 - **Missing data on the outcome (attrition)** is especially a problem if the patterns of missingness are caused by the treatment itself. This is the most common problem.

     - Do not drop observations that are missing outcome data from your analysis.

     - You may be able to **bound** estimates of treatment effects.

 - **Non-compliance**. The effect of treatment assignment is not the same as the effect of receiving the treatment.  Sometimes units will not comply with their assigned treatment status, but not all hope is lost.
 
     - One-sided compliance occurs when some units assigned to treatment fail to take the treatment, but all units assigned to control do not take the treatment.
 
     - The local average treatment effect (LATE, also known as the complier average causal effect, CACE) is the average effect for the units that take the treatment when assigned, but not otherwise. If the monotonicity assumption and the exclusion restriction hold, we may be able to estimate LATE.

 - **"Spillover effects" or interference between units** is a violation of one of the core assumptions for causal inference ([causal inference](causalinference.html)).
     
      - However, this may not be a problem if you are interested in spillover effects and/or have designed your research to account for it.
 
 - **Hawthorne effects** are when subjects behave differently because they are being observed.  
 
- **Non-excludability**. Treating treatment and control units differently, such as with different data collection processes or extra attention to the treated units, can confuse interpretation of experimental results.

     - If Hawthorne effects are present for treated units but not control units, then we have a violation of the excludability assumption.  
     



## Slides

Below are slides with the core content that we cover in our lecture on threats to the internal validity of randomized experiments. You can directly use these slides or make your local copy and edit.

 - [R Markdown Source](https://egap.github.io/learningdays-resources/Slides/threats-slides.Rmd)

 - [PDF version](https://egap.github.io/learningdays-resources/Slides/threats-slides.pdf)

 - [HTML version](https://egap.github.io/learningdays-resources/Slides/threats-slides.html)

You can also see the slides used in previous EGAP Learning Days:

- [The threats presentation from EGAP Learning Days at the African School of Economics, Abomey-Calavi, June 2019 (first section reviews randomization designs)](https://egap.github.io/learningdays-resources/Slides/Examples/threats-benin.pdf)

- [The attrition and missing data presentation from EGAP Learning Days at Universidad Diego Portales in Santiago, Chile, May 2016](https://egap.github.io/learningdays-resources/Slides/Examples/threats-santiago.pdf)

## Resources

### EGAP Methods Guide

- EGAP Methods Guide [10 Things to Know about Missing Data](https://egap.org/resource/10-things-to-know-about-missing-data/)

- EGAP Methods Guide [10 Types of Treatment Effect You Should Know About](https://egap.org/resource/10-types-of-treatment-effect-you-should-know-about/)

- EGAP Methods Guide [10 Things to Know about the Local Average Treatment Effect](https://egap.org/resource/10-things-to-know-about-the-local-average-treatment-effect/)

### Books, Chapters, and Articles

- [Standard operating procedures for Don Green’s lab at Columbia University](https://github.com/acoppock/Green-Lab-SOP). A comprehensive set of procedures and rules of thumb for conducting experimental studies.
- [@gerber_field_2012, Chapters 5--8] These chapters address non-compliance, attrition, and interference.

### EGAP Policy Briefs

- [EGAP Policy Brief 11: Election Observers and Fraud in Ghana ](https://egap.org/resource/brief-11-election-observers-and-fraud-in-ghana/)

- [EGAP Policy Brief 16: Spillover Effects of Observers in Ghana ](https://egap.org/resource/brief-16-spillover-effects-of-observers-in-ghana/)
